apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: dGFza2Z5ZXItcm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: dGFza2Z5ZXItcGFzcw== 
  MONGO_URI: bW9uZ29kYjovL21vbmdvOjI3MDE3L1Rhc2tmeWVyREI=
  PORT: NDAwMA==
  JWT_SECRET: a2x0NHRDb3ZkeU5FTjh0UHRUbjM3UXJ6RUN4eDd6V0lXQTFtd0RyN2hMSQ==
