name: taskfyer

services:
  frontend:
    build:
      context: ../frontend
      target: production
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000/api/v1
    ports:
      - "3000:3000"
    env_file: ../frontend/prod.env
    depends_on:
      - backend
    networks:
      - taskfyer_network

  backend:
    build:
      context: ../backend
      target: production
    ports:
      - "8000:8000"
    env_file: ../backend/prod.env
    depends_on:
      - mongodb
    networks:
      - taskfyer_network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - taskfyer_network

volumes:
  mongodb_data:

networks:
  taskfyer_network:
    driver: bridge
