name: taskfyer

services:
  frontend:
    build:
      context: ../frontend
      target: production
      args:
        NEXT_PUBLIC_API_URL: http://${API_DOMAIN_NAME}/api/v1
    env_file: ../frontend/prod.env
    environment:
      - NEXT_PUBLIC_API_URL=http://${API_DOMAIN_NAME}/api/v1
    depends_on:
      - backend
    networks:
      - taskfyer_network

  backend:
    build:
      context: ../backend
      target: production
    env_file: ../backend/prod.env
    environment:
      - CLIENT_URL=http://${DOMAIN_NAME}
    depends_on:
      - mongodb
    networks:
      - taskfyer_network

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - taskfyer_network

  nginx:
    build:
      context: ../nginx
    ports:
      - "80:80"
    env_file: .env
    depends_on:
      - frontend
      - backend
    networks:
      - taskfyer_network

volumes:
  mongodb_data:

networks:
  taskfyer_network:
    driver: bridge
