name: taskfyer

services:
  frontend:
    build:
      context: ../frontend
      target: production
    env_file: ../frontend/prod.env
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api/v1
    depends_on:
      - backend
    networks:
      - taskfyer_network

  backend:
    build:
      context: ../backend
      target: production
    env_file: ../backend/prod.env
    environment:
      - CLIENT_URL=http://localhost
    depends_on:
      - mongodb
    networks:
      - taskfyer_network

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - taskfyer_network

  nginx:
    image: nginx
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - taskfyer_network

volumes:
  mongodb_data:

networks:
  taskfyer_network:
    driver: bridge
