apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: taskfyer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jordanvives/taskfyer:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://backend.taskfyer.svc.cluster.local:4000/api/v1"
