apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: taskfyer
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  clusterIP: None  # Internal service, not accessible externally
